language: python
python: "3.8.2"
cache: pip
env:
  - DJANGO_VERSION=3.0.5
install:
  - pip install -r requirements.txt
script:
  - coverage run --source antiphona_app pytest tests/
after_success:
  - coveralls
