# Generated by Django 3.0.5 on 2020-04-13 05:10

import antiphona_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Antiphona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Antiphona_Missa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evangelium', models.CharField(blank=True, max_length=80, null=True)),
                ('psalm', models.CharField(blank=True, max_length=80)),
                ('alt_psalm', models.CharField(blank=True, max_length=80)),
                ('anno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='antiphona_app.Anno')),
                ('antiphona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiphona_app.Antiphona')),
            ],
        ),
        migrations.CreateModel(
            name='AntiphonaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Documentum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MissaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=40)),
                ('author', models.CharField(blank=True, max_length=40)),
                ('audio_link', models.URLField(blank=True, max_length=120)),
                ('sheet_link', models.URLField(blank=True, max_length=120)),
                ('similarity', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('antiphona_missa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiphona_app.Antiphona_Missa')),
            ],
        ),
        migrations.CreateModel(
            name='MissaType_AntiphonaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('antiphona_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiphona_app.AntiphonaType')),
                ('missa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiphona_app.MissaType')),
            ],
        ),
        migrations.AddField(
            model_name='missatype',
            name='antiphona_types',
            field=models.ManyToManyField(through='antiphona_app.MissaType_AntiphonaType', to='antiphona_app.AntiphonaType'),
        ),
        migrations.CreateModel(
            name='Missa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('antiphonae', models.ManyToManyField(through='antiphona_app.Antiphona_Missa', to='antiphona_app.Antiphona')),
                ('missae_type', models.ForeignKey(default=antiphona_app.models.MissaType.get_default_missa_type, on_delete=django.db.models.deletion.SET_DEFAULT, to='antiphona_app.MissaType')),
            ],
        ),
        migrations.AddField(
            model_name='antiphona_missa',
            name='antiphona_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antiphona_app.AntiphonaType'),
        ),
        migrations.AddField(
            model_name='antiphona_missa',
            name='documentum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='antiphona_app.Documentum'),
        ),
        migrations.AddField(
            model_name='antiphona_missa',
            name='missa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='antiphona_app.Missa'),
        ),
        migrations.AddField(
            model_name='antiphona',
            name='missae',
            field=models.ManyToManyField(through='antiphona_app.Antiphona_Missa', to='antiphona_app.Missa'),
        ),
    ]
