# Generated by Django 3.0.5 on 2020-04-13 05:12

from django.db import migrations


def initial_data_population(apps, schema_editor):
    # Anno population
    Anno = apps.get_model('antiphona_app', 'Anno')
    for anno in ('A', 'B', 'C', 'I', 'II'):
        Anno.objects.create(name=anno)

    # Antiphona population
    AntiphonaType = apps.get_model('antiphona_app', 'AntiphonaType')
    introito = AntiphonaType.objects.create(name='Introito')
    offertorium = AntiphonaType.objects.create(name='Offertorium')
    communio = AntiphonaType.objects.create(name='Communio')

    # Missa population
    MissaType = apps.get_model('antiphona_app', 'MissaType')
    for missa_type_name in ('Dominica', 'Feria'):
        missa_type = MissaType.objects.create(name=missa_type_name)
        missa_type.antiphona_types.add(introito, through_defaults={'order': 1})
        missa_type.antiphona_types.add(offertorium, through_defaults={'order': 2})
        missa_type.antiphona_types.add(communio, through_defaults={'order': 3})

    # Documentum population
    Documentum = apps.get_model('antiphona_app', 'Documentum')
    for documentum in ('Missale Romanum', 'Graduale Romanum', 'Graduale Simplex'):
        Documentum.objects.create(name=documentum)


class Migration(migrations.Migration):

    dependencies = [
        ('antiphona_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_data_population),
    ]
