# Generated by Django 3.0.5 on 2020-04-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiphona_app', '0002_auto_20200413_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missa',
            old_name='missae_type',
            new_name='missa_type',
        ),
    ]
